### ISSUE TITLE
Добавьте .env.example

### ISSUE THREAD

**Issue by Blezigen** [dota2classic/game-coordinator#1]
Не понятно какие параметры есть в вашем .env
Что-бы не делать всю работу с нуля просьба разместить в коде .evn.example ваши переменные локального окружения.
Нашел пока:
DISCORD_SERVER_ID
DISCORD_API_TOKEN
DISCORD_GATEWAY_HOST
CORE_GATEWAY_HOST
REDIS_URL
REDIS_PASSWORD
PROFILE

Это все переменные?

**Comment by enchantinggg4** [comment]
Скоро добавлю

**Comment by enchantinggg4** [comment]
fixed in https://github.com/dota2classic/game-coordinator/commit/95af2a33fc17460993206e76b612746b45b103af
